name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_SERVER_URL: ${{ secrets.PYTHON_SERVER_URL }}
      JAVA_SERVER_URL:   ${{ secrets.JAVA_SERVER_URL }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dev tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git curl wget vim unzip

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dev packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flask requests pytest black mypy

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Download & install Python server
        run: |
          URL="${PYTHON_SERVER_URL:-https://example.com/path/to/python-server.tar.gz}"
          if [[ "$URL" == *"example.com"* ]]; then
            echo "::warning ::PYTHON_SERVER_URL is not set or placeholder; skipping download"
          else
            echo "Downloading Python server from $URL"
            curl -fSL "$URL" -o python-server.tar.gz || { echo "::error ::Failed to download Python server"; exit 1; }
            sudo mkdir -p /opt/python-server
            sudo tar -xzf python-server.tar.gz -C /opt/python-server
            python -m pip install --upgrade pip setuptools wheel
            if [ -f /opt/python-server/requirements.txt ]; then
              pip install -r /opt/python-server/requirements.txt
            else
              echo "::warning ::requirements.txt not found in /opt/python-server"
            fi
          fi

      - name: Download & install Java server
        run: |
          URL="${JAVA_SERVER_URL:-https://example.com/path/to/java-server.zip}"
          if [[ "$URL" == *"example.com"* ]]; then
            echo "::warning ::JAVA_SERVER_URL is not set or placeholder; skipping download"
          else
            echo "Downloading Java server from $URL"
            curl -fSL "$URL" -o java-server.zip || { echo "::error ::Failed to download Java server"; exit 1; }
            sudo mkdir -p /opt/java-server
            sudo unzip -q java-server.zip -d /opt/java-server
            cd /opt/java-server
            mvn clean install -DskipTests
          fi

      - name: Update security policies & materials
        run: python scripts/update_docs.py

      - name: Commit & push updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --quiet --cached || (git commit -m "chore: update information security regulations & materials" && git push)

      - name: Verify installation
        run: |
          python --version
          java -version
          mvn -v
          pip show flask requests pytest black mypy || true
