name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 1) 환경 변수: 비어 있으면 기본 URL로 대체
    env:
      PYTHON_SERVER_URL: ${{ secrets.PYTHON_SERVER_URL }}
      JAVA_SERVER_URL:   ${{ secrets.JAVA_SERVER_URL }}

    steps:
      # 2) 코드 체크아웃 (커밋 푸시 가능)
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 3) 개발 도구 설치
      - name: Install dev tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git curl wget vim unzip

      # 4) Python 환경 및 패키지 설치
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python dev packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flask requests pytest black mypy

      # 5) Java 환경 및 Maven 설치
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Install Maven
        run: sudo apt-get install -y maven

      # 6) Python 서버 다운로드 & 설치
      - name: Download & install Python server
        run: |
          # 비어 있으면 기본 URL로 설정
          URL="${PYTHON_SERVER_URL:-https://example.com/path/to/python-server.tar.gz}"
          echo "Downloading Python server from $URL"
          curl -fSL "$URL" -o python-server.tar.gz \
            || { echo "::error ::Failed to download Python server"; exit 1; }
          sudo mkdir -p /opt/python-server
          sudo tar -xzf python-server.tar.gz -C /opt/python-server
          python -m pip install --upgrade pip setuptools wheel
          if [ -f /opt/python-server/requirements.txt ]; then
            pip install -r /opt/python-server/requirements.txt
          else
            echo "::warning ::requirements.txt not found"
          fi

      # 7) Java 서버 다운로드 & 설치
      - name: Download & install Java server
        run: |
          # 비어 있으면 기본 URL로 설정
          URL="${JAVA_SERVER_URL:-https://example.com/path/to/java-server.zip}"
          echo "Downloading Java server from $URL"
          curl -fSL "$URL" -o java-server.zip \
            || { echo "::error ::Failed to download Java server"; exit 1; }
          sudo mkdir -p /opt/java-server
          sudo unzip -q java-server.zip -d /opt/java-server
          cd /opt/java-server
          mvn clean install -DskipTests

      # 8) 정보보호 규정 및 자료집 업데이트
      - name: Update security policies & materials
        run: python scripts/update_docs.py

      # 9) 변경된 문서 커밋 & 푸시
      - name: Commit & push updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --quiet --cached || \
            (git commit -m "chore: update information security regulations & materials" && git push)

      # 10) 설치 상태 검증
      - name: Verify installation
        run: |
          python --version
          java -version
          mvn -v
          pip show flask requests pytest black mypy || true
