name: CI

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # If the secret is not set, fall back to a known URL
      PYTHON_SERVER_URL: ${{ secrets.PYTHON_SERVER_URL || 'https://example.com/path/to/python-server.tar.gz' }}
      JAVA_SERVER_URL:   ${{ secrets.JAVA_SERVER_URL   || 'https://example.com/path/to/java-server.zip' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install dev tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git curl wget vim unzip maven python3-pip

      - name: Set up Python & Java
        uses:
          - actions/setup-python@v4
          - actions/setup-java@v3
        with:
          python-version: '3.x'
          distribution: temurin
          java-version: '17'

      - name: Install Python dev packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flask requests pytest black mypy

      - name: Download & install Python server
        run: |
          echo "Downloading Python server from $PYTHON_SERVER_URL"
          curl -fSL "$PYTHON_SERVER_URL" -o python-server.tar.gz
          sudo mkdir -p /opt/python-server
          sudo tar -xzf python-server.tar.gz -C /opt/python-server
          python -m pip install --upgrade pip setuptools wheel
          if [ -f /opt/python-server/requirements.txt ]; then
            pip install -r /opt/python-server/requirements.txt
          fi

      - name: Download & install Java server
        run: |
          echo "Downloading Java server from $JAVA_SERVER_URL"
          curl -fSL "$JAVA_SERVER_URL" -o java-server.zip
          sudo mkdir -p /opt/java-server
          sudo unzip -q java-server.zip -d /opt/java-server
          pushd /opt/java-server
          mvn clean install -DskipTests
          popd

      - name: Generate security organization docs
        run: |
          mkdir -p docs
          cat << 'EOF' > docs/organization.md
          # 정보보호 조직 자료집

          *Updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ') UTC*

          ## 1. CISO (Chief Information Security Officer)
          ### 1.1 정의  
          조직 내 정보보호 전략·정책·거버넌스를 총괄하는 최고 책임자
          ### 1.2 주요 책임  
          - 정보보호 전략 수립·운영  
            - 전사 보안 비전·로드맵 설계  
            - 예산·투자 우선순위 결정  
          - 정책·표준·절차 관리  
            - 보안 정책, 가이드라인, 실행 절차 제정  
          - 위험 관리(Risk Management)  
            - 자산 식별 → 위협·취약점 평가 → 대응 계획 수립  
          - 보안 운영(Security Operations)  
            - SOC 운영, 침해 탐지·모니터링, 취약점 검사  
          - 사고 대응(Incident Response)  
            - CSIRT 조직 관리, 사고 조사·대응·복구  
          - 컴플라이언스 및 감사  
            - ISO 27001, ISMS-P 등 인증·준수 활동 지원

          ### 1.3 보고 체계  
          - 보고 대상: CEO 또는 이사회  
          - 주요 산출물: 월간/분기별 보안 리포트, KPI 보고, 사고 현황 보고

          ### 1.4 필요 역량  
          - 리더십·거버넌스 이해  
          - 정보보호 기술·방법론  
          - 위험 관리 및 컴플라이언스 지식  
          - 커뮤니케이션·프레젠테이션 능력

          ## 2. CPO (Chief Privacy Officer)
          ### 2.1 정의  
          개인정보 보호·프라이버시 거버넌스를 총괄하는 최고 책임자
          ### 2.2 주요 책임  
          - 개인정보 보호 정책 수립 (GDPR, CCPA, PIPA 반영)  
          - 프라이버시 영향 평가(PIA) 수행  
          - 데이터 거버넌스(분류·보관·파기 기준 수립)  
          - 컴플라이언스 관리 (내부 감사·규제 대응)  
          - 교육·인식 제고 (전사 개인정보 보호 교육·모의 점검)
          ### 2.3 보고 체계  
          - 보고 대상: 법무총괄(CLO) 또는 CEO  
          - 주요 산출물: PIA 보고서, 규제 준수 리포트, 교육 이행 현황
          ### 2.4 필요 역량  
          - 개인정보 보호법·지침 이해  
          - 데이터 흐름도·PIA 평가 기법  
          - 법무·컴플라이언스 경험  
          - 윤리적 판단 및 커뮤니케이션 역량

          ## 3. CISO vs CPO 비교
          | 구분       | CISO                         | CPO                 |
          |-----------|------------------------------|---------------------|
          | 목표      | 기밀성·무결성·가용성 보장    | 개인정보 보호·준수  |
          | 핵심 활동 | 보안 정책·침해 대응·SOC 운영 | PIA·분류·교육       |
          | 이해관계자| IT·보안팀·경영진             | 법무·감사팀         |
          | 컴플라이언스| ISO27001·ISMS-P            | GDPR·CCPA·PIPA      |
          | 보고 라인 | CEO → CISO → SOC             | CEO → CPO → 담당자  |

          ## 4. 협업 및 거버넌스
          ```mermaid
          flowchart LR
            Board[이사회] --> CEO
            CEO --> CISO
            CEO --> CPO
            CISO --> SOC
            CPO --> Legal
            CISO --> IT
            CPO --> IT
          ```
          EOF

      - name: Commit & push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/organization.md
          git diff --quiet --cached || git commit -m "chore: update security regulations & materials"
          git push

      - name: Summary
        run: |
          echo "=== Installation & Docs Summary ==="
          if [ -d /opt/python-server ]; then
            echo "Python server installed under /opt/python-server:"
            ls /opt/python-server
          else
            echo "Python server NOT installed"
          fi
          if [ -d /opt/java-server ]; then
            echo "Java server installed under /opt/java-server:"
            ls /opt/java-server
          else
            echo "Java server NOT installed"
          fi
          echo "Docs file:"
          cat docs/organization.md | head -n 5
