# .github/workflows/ci.yml
name: CI

permissions:
  contents: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # 비어있으면 기본 URL로 대체
      PYTHON_SERVER_URL: ${{ secrets.PYTHON_SERVER_URL || 'https://example.com/path/to/python-server.tar.gz' }}
      JAVA_SERVER_URL:   ${{ secrets.JAVA_SERVER_URL   || 'https://example.com/path/to/java-server.zip' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install dev tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git curl wget vim unzip maven python3-pip

      - name: Set up Python & Java
        uses:
          - actions/setup-python@v4
          - actions/setup-java@v3
        with:
          python-version: '3.x'
          distribution: temurin
          java-version: '17'

      - name: Install Python packages
        run: pip install --upgrade flask requests pytest black mypy

      - name: Download & install Python server
        run: |
          echo "Downloading Python server from $PYTHON_SERVER_URL"
          curl -fSL "$PYTHON_SERVER_URL" -o python-server.tar.gz
          sudo mkdir -p /opt/python-server
          sudo tar -xzf python-server.tar.gz -C /opt/python-server
          if [ -f /opt/python-server/requirements.txt ]; then
            pip install -r /opt/python-server/requirements.txt
          fi

      - name: Download & install Java server
        run: |
          echo "Downloading Java server from $JAVA_SERVER_URL"
          curl -fSL "$JAVA_SERVER_URL" -o java-server.zip
          sudo mkdir -p /opt/java-server
          sudo unzip -q java-server.zip -d /opt/java-server
          pushd /opt/java-server
          mvn clean install -DskipTests
          popd

      - name: Generate security organization docs
        run: |
          mkdir -p docs
          cat > docs/organization.md << 'EOF'
# 정보보호 조직 자료집

*Updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ') UTC*

## 1. CISO (Chief Information Security Officer)

### 1.1 정의  
조직 내 정보보호 전략·정책·거버넌스를 총괄하는 최고 책임자

### 1.2 주요 책임  
- 정보보호 전략 수립·운영  
  - 전사 보안 비전·로드맵 설계  
  - 예산·투자 우선순위 결정  
- 정책·표준·절차 관리  
  - 보안 정책, 가이드라인, 실행 절차 제정  
- 위험 관리(Risk Management)  
  - 자산 식별 → 위협·취약점 평가 → 대응 계획 수립  
- 보안 운영(Security Operations)  
  - SOC 운영, 침해 탐지·모니터링, 취약점 검사  
- 사고 대응(Incident Response)  
  - CSIRT 조직 관리, 사고 조사·대응·복구  
- 컴플라이언스 및 감사  
  - ISO 27001, ISMS-P 등 인증·준수 활동 지원

### 1.3 보고 체계  
- 보고 대상: CEO 또는 이
