jobs:
  synthetics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install        # ← ci → install 로 변경

      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v1.4.0
        with:
          api_key:     ${{ secrets.DD_API_KEY }}
          app_key:     ${{ secrets.DD_APP_KEY }}
          site:        ${{ secrets.DD_SITE }}
          test_search_query: "tag:e2e-tests"
