# .github/workflows/python-ci.yml
name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Start HTTP server
        run: |
          # Start a simple HTTP server in background
          nohup python -m http.server 8000 > server.log 2>&1 &
          # Wait up to 20s for the server to respond
          for i in {1..10}; do
            if curl -sf http://localhost:8000; then
              echo "✅ Server is up"
              break
            fi
            echo "⏳ Waiting for server..."
            sleep 2
          done

      - name: Check server connection
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000)
          if [ "$status" != "200" ]; then
            echo "::error ::Expected HTTP 200 but got $status"
            exit 1
          fi
          echo "✅ Received HTTP 200 from server"

      - name: Lint with flake8
        run: |
          # fail on syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # treat other issues as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: pytest
